### ISSUE TITLE
Working with Windows XP ?

### ISSUE THREAD

**Issue by maxence-vanhaezebroeke** [Thomas-Deasington/city-plan-trip#1]

**Comment by Thomas-Deasington** [comment]
No it's not working with Windows XP, sorry mate @maxence-vanhaezebroeke 
![image](https://user-images.githubusercontent.com/58557410/231090613-59b0210d-cbd0-485a-a485-6371ddcbda97.png)

**Comment by maxence-vanhaezebroeke** [comment]
You sure there is no way to make it work ... ? My company is only using Windows XP, 50 users here, so it could be really helpful to have this app...

**Comment by Thomas-Deasington** [comment]
![image](https://user-images.githubusercontent.com/58557410/231272710-7a6c56d0-3800-435a-a35b-a663d6088f50.png)
